### PR TITLE
Added Ivo Balbaert

### PR DESCRIPTION
**Pull request by Ivo-Balbaert**
Coud you please help me:
I forked, cloned it to a local repository, added my json file, updated my fork, and then did a pull request: which says only 1 file (the one I added) was changed.
I don't know what went wrong, or how I should do it otherwise.
Thanks.

### CODE REVIEW

**Comment by Ivo-Balbaert** [comment]
Coud you please help me:
I forked, cloned it to a local repository, added my json file, updated my fork, and then did a pull request: which says only 1 file (the one I added) was changed.
I don't know what went wrong, or how I should do it otherwise.
Thanks.

**Comment by nrc** [comment]
@Ivo-Balbaert you need to rename the file in your PR from `ibalbaert.json` to `Ivo-Balbaert.json`, then it should work fine. (The filename must match your GitHub username exactly so that you can only modify your own details).

**Comment by nrc** [comment]
Let me know if you're still having problems with it

**Comment by Ivo-Balbaert** [comment]
Thanks for the help Nick!

 

Ivo

**Pull request merged**
