### PR TITLE
Mzz-Tanmay.json

### PR DESCRIPTION
**Pull request by Mzz-Tanmay**
{
    "name": "MzzTanmay",
    "irc": "mzztanmay",
    "irc_channels": [#rust],
    "show_avatar": true,
    "email": "mzz.tanmay@gmail.com",
    "discourse": "mzztanmay",
    "reddit": "Mzz_Tanmay",
    "twitter": "@mzztanmay",
    "blog": "http://www.somewhereinblog.net/blog/mzz_tanmay",
    "website": "https://mzztanmayblog.wordpress.com/",
    "notes": "I am a student of MBSTU. i am very interested of Mozilla"
    }

### CODE REVIEW

**Comment by Mzz-Tanmay** [comment]
now what's my wrong???

**Comment by nrc** [comment]
> Unexpected token + in JSON at position 0

There is a `+` at the start of most lines - looks like you copied the diff?

**Comment by Mzz-Tanmay** [comment]
Now this is correct?? or wrong??

**Comment by Mzz-Tanmay** [comment]
thanks

**Pull request merged**
