### PR TITLE
Mzz-Tanmay.json

### PR DESCRIPTION
**Pull request by Mzz-Tanmay**
Mzz-Tanmay.json
+{

+    "name": "MzzTanmay",
+    "irc": "mzztanmay",
+    "irc_channels": [rust],
+    "show_avatar": true,
+    "email": "mzz.tanmay@gmail.com",
+    "discourse": "mzztanmay",
+    "reddit": "Mzz_Tanmay",
+    "twitter": "@MzzTanmay",
+    "blog": "http://www.somewhereinblog.net/blog/mzz_tanmay",
+    "website": "https://mzztanmayblog.wordpress.com/",
+    "notes": "I am a student of MBSTU. i am very interested of Mozilla"
+}

### CODE REVIEW

**Comment by Mzz-Tanmay** [comment]
i can not understand ..what's my wrong!!!

**Comment by nrc** [comment]
The file you created must have a .json extension

**Comment by Mzz-Tanmay** [comment]
i can not understand ..what's my wrong!!!

**Comment by Mzz-Tanmay** [comment]
now this is correct?? or not??

**Comment by nrc** [comment]
The file still does not have a json extension

**Comment by Mzz-Tanmay** [comment]
how can i give json extension??

**Comment by nrc** [comment]
Rename the file on disk:

```
mv Mzz-TanMay Mzz-Tanmay.json
git add Mzz-Tanmay.json
git commit --amend
git push origin master -f
```

**Pull request closed without merging**
